title: Just the Docs Test
description: A test of the just the docs theme
theme: just-the-docs

url: https://nineteendo.github.io/just-the-docs-test

aux_links:
  Template Repository: https://github.com/nineteendo/just-the-docs-test
